[2024-06-03T17:38:07.036+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:38:07.050+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2024-06-03T17:38:07.056+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2024-06-03T17:38:07.056+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:38:07.066+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-01-01 00:00:00+00:00
[2024-06-03T17:38:07.070+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=73) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:38:07.071+0000] {standard_task_runner.py:63} INFO - Started process 78 to run task
[2024-06-03T17:38:07.072+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-01-01T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpv8fv8nrk']
[2024-06-03T17:38:07.073+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask blunders_etl
[2024-06-03T17:38:07.106+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-01-01T00:00:00+00:00 [running]> on host a5a4421409ea
[2024-06-03T17:38:07.163+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-01-01T00:00:00+00:00'
[2024-06-03T17:38:07.164+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:38:07.165+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:38:07.171+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:38:07.177+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chess_dag.py", line 23, in blunders_etl_task
    return get_monthly_blunders(execution_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/blunder_etl_code.py", line 89, in get_monthly_blunders
    connection = BaseHook.get_connection('chess_project_s3')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `chess_project_s3` isn't defined
[2024-06-03T17:38:07.184+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-01-01T00:00:00+00:00, execution_date=20190101T000000, start_date=20240603T173807, end_date=20240603T173807
[2024-06-03T17:38:07.194+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task blunders_etl (The conn_id `chess_project_s3` isn't defined; 78)
[2024-06-03T17:38:07.205+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-03T17:38:07.216+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:38:07.217+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-03T17:44:29.467+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:44:29.483+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2024-06-03T17:44:29.488+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2024-06-03T17:44:29.488+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:44:29.498+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-01-01 00:00:00+00:00
[2024-06-03T17:44:29.502+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=66) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:44:29.504+0000] {standard_task_runner.py:63} INFO - Started process 70 to run task
[2024-06-03T17:44:29.504+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-01-01T00:00:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp53fcvqe9']
[2024-06-03T17:44:29.505+0000] {standard_task_runner.py:91} INFO - Job 67: Subtask blunders_etl
[2024-06-03T17:44:29.539+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-01-01T00:00:00+00:00 [running]> on host f55fff24b127
[2024-06-03T17:44:29.604+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-01-01T00:00:00+00:00'
[2024-06-03T17:44:29.605+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:44:29.605+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:44:29.612+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-03T17:44:30.575+0000] {logging_mixin.py:188} INFO - No games for period 2019_01
[2024-06-03T17:44:30.575+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-03T17:44:30.576+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:44:30.582+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-01-01T00:00:00+00:00, execution_date=20190101T000000, start_date=20240603T174429, end_date=20240603T174430
[2024-06-03T17:44:30.600+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-03T17:44:30.611+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:44:30.613+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:09:55.228+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:09:55.244+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2024-06-08T14:09:55.250+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2024-06-08T14:09:55.250+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:09:55.260+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-01-01 00:00:00+00:00
[2024-06-08T14:09:55.265+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=82) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:09:55.266+0000] {standard_task_runner.py:63} INFO - Started process 85 to run task
[2024-06-08T14:09:55.267+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-01-01T00:00:00+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp4489ztvt']
[2024-06-08T14:09:55.267+0000] {standard_task_runner.py:91} INFO - Job 206: Subtask blunders_etl
[2024-06-08T14:09:55.310+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-01-01T00:00:00+00:00 [running]> on host 3c9d89bfdaf1
[2024-06-08T14:09:55.364+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-01-01T00:00:00+00:00'
[2024-06-08T14:09:55.365+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:09:55.366+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:09:55.374+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:09:56.434+0000] {logging_mixin.py:188} INFO - No games for period 2019_01
[2024-06-08T14:09:56.435+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T14:09:56.435+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:09:56.444+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-01-01T00:00:00+00:00, execution_date=20190101T000000, start_date=20240608T140955, end_date=20240608T140956
[2024-06-08T14:09:56.482+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T14:09:56.496+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T14:09:56.497+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:51:23.372+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:51:23.390+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2024-06-08T14:51:23.396+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2024-06-08T14:51:23.396+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:51:23.408+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-01-01 00:00:00+00:00
[2024-06-08T14:51:23.414+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=192) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:51:23.416+0000] {standard_task_runner.py:63} INFO - Started process 196 to run task
[2024-06-08T14:51:23.415+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-01-01T00:00:00+00:00', '--job-id', '243', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpu5t248_b']
[2024-06-08T14:51:23.416+0000] {standard_task_runner.py:91} INFO - Job 243: Subtask blunders_etl
[2024-06-08T14:51:23.450+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-01-01T00:00:00+00:00 [running]> on host bf0ade909435
[2024-06-08T14:51:23.503+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-01-01T00:00:00+00:00'
[2024-06-08T14:51:23.505+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:51:23.506+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:51:23.512+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:51:24.488+0000] {logging_mixin.py:188} INFO - No games for period 2019_01
[2024-06-08T14:51:24.488+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T14:51:24.488+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:51:24.496+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-01-01T00:00:00+00:00, execution_date=20190101T000000, start_date=20240608T145123, end_date=20240608T145124
[2024-06-08T14:51:24.511+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T14:51:24.523+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T14:51:24.524+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
