[2024-07-07T18:13:30.048+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T18:13:30.064+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.redshift_game_load scheduled__2020-05-01T00:00:00+00:00 [queued]>
[2024-07-07T18:13:30.071+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.redshift_game_load scheduled__2020-05-01T00:00:00+00:00 [queued]>
[2024-07-07T18:13:30.071+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-07T18:13:30.081+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): redshift_game_load> on 2020-05-01 00:00:00+00:00
[2024-07-07T18:13:30.085+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1064) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-07T18:13:30.086+0000] {standard_task_runner.py:63} INFO - Started process 1067 to run task
[2024-07-07T18:13:30.087+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'redshift_game_load', 'scheduled__2020-05-01T00:00:00+00:00', '--job-id', '423', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpkitory13']
[2024-07-07T18:13:30.088+0000] {standard_task_runner.py:91} INFO - Job 423: Subtask redshift_game_load
[2024-07-07T18:13:30.120+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.redshift_game_load scheduled__2020-05-01T00:00:00+00:00 [running]> on host cb919e35e0e9
[2024-07-07T18:13:30.178+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='redshift_game_load' AIRFLOW_CTX_EXECUTION_DATE='2020-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-05-01T00:00:00+00:00'
[2024-07-07T18:13:30.179+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T18:13:30.180+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-07-07T18:13:30.186+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-07-07T18:13:30.979+0000] {base.py:84} INFO - Using connection ID 'chess_project_redshift' for task execution.
[2024-07-07T18:14:00.386+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T18:14:00.386+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chess_dag.py", line 27, in redshift_game_task
    return load_game_data(execution_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/redshift_etl_code.py", line 107, in load_game_data
    cursor.execute(drop_games_staging_query)
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/cursor.py", line 248, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/cursor.py", line 241, in execute
    self._c.execute(self, operation, args)
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/core.py", line 1987, in execute
    self.handle_messages(cursor)
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/core.py", line 2194, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': 'XX000', 'M': 'could not open relation with OID 200391', 'F': '../src/pg/src/backend/access/heap/heapam.c', 'L': '636', 'R': 'local_relation_open'}
[2024-07-07T18:14:00.394+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=chess_etl, task_id=redshift_game_load, run_id=scheduled__2020-05-01T00:00:00+00:00, execution_date=20200501T000000, start_date=20240707T181330, end_date=20240707T181400
[2024-07-07T18:14:00.402+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 423 for task redshift_game_load ({'S': 'ERROR', 'C': 'XX000', 'M': 'could not open relation with OID 200391', 'F': '../src/pg/src/backend/access/heap/heapam.c', 'L': '636', 'R': 'local_relation_open'}; 1067)
[2024-07-07T18:14:00.431+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-07T18:14:00.442+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-07T18:14:00.443+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-07T23:11:11.530+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T23:11:11.544+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.redshift_game_load scheduled__2020-05-01T00:00:00+00:00 [queued]>
[2024-07-07T23:11:11.549+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.redshift_game_load scheduled__2020-05-01T00:00:00+00:00 [queued]>
[2024-07-07T23:11:11.549+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-07T23:11:11.557+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): redshift_game_load> on 2020-05-01 00:00:00+00:00
[2024-07-07T23:11:11.563+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=13268) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-07T23:11:11.564+0000] {standard_task_runner.py:63} INFO - Started process 13270 to run task
[2024-07-07T23:11:11.564+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'redshift_game_load', 'scheduled__2020-05-01T00:00:00+00:00', '--job-id', '626', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpchyg7us8']
[2024-07-07T23:11:11.565+0000] {standard_task_runner.py:91} INFO - Job 626: Subtask redshift_game_load
[2024-07-07T23:11:11.597+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.redshift_game_load scheduled__2020-05-01T00:00:00+00:00 [running]> on host 6569f5155f0c
[2024-07-07T23:11:11.652+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='redshift_game_load' AIRFLOW_CTX_EXECUTION_DATE='2020-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-05-01T00:00:00+00:00'
[2024-07-07T23:11:11.653+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T23:11:11.654+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-07-07T23:11:11.660+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-07-07T23:11:12.495+0000] {base.py:84} INFO - Using connection ID 'chess_project_redshift' for task execution.
[2024-07-07T23:11:39.121+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-07T23:11:39.122+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T23:11:39.130+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=redshift_game_load, run_id=scheduled__2020-05-01T00:00:00+00:00, execution_date=20200501T000000, start_date=20240707T231111, end_date=20240707T231139
[2024-07-07T23:11:39.176+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-07T23:11:39.190+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-07T23:11:39.191+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
