[2024-06-03T17:39:24.654+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:39:24.670+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-10-01T00:00:00+00:00 [queued]>
[2024-06-03T17:39:24.676+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-10-01T00:00:00+00:00 [queued]>
[2024-06-03T17:39:24.677+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:39:24.686+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2021-10-01 00:00:00+00:00
[2024-06-03T17:39:24.691+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=230) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:39:24.693+0000] {standard_task_runner.py:63} INFO - Started process 234 to run task
[2024-06-03T17:39:24.692+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2021-10-01T00:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpj1mftswj']
[2024-06-03T17:39:24.693+0000] {standard_task_runner.py:91} INFO - Job 57: Subtask blunders_etl
[2024-06-03T17:39:24.726+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2021-10-01T00:00:00+00:00 [running]> on host a5a4421409ea
[2024-06-03T17:39:24.782+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2021-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-10-01T00:00:00+00:00'
[2024-06-03T17:39:24.783+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:39:24.784+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:39:24.789+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:39:24.794+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chess_dag.py", line 23, in blunders_etl_task
    return get_monthly_blunders(execution_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/blunder_etl_code.py", line 89, in get_monthly_blunders
    connection = BaseHook.get_connection('chess_project_s3')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `chess_project_s3` isn't defined
[2024-06-03T17:39:24.799+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2021-10-01T00:00:00+00:00, execution_date=20211001T000000, start_date=20240603T173924, end_date=20240603T173924
[2024-06-03T17:39:24.807+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 57 for task blunders_etl (The conn_id `chess_project_s3` isn't defined; 234)
[2024-06-03T17:39:24.826+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-03T17:39:24.836+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:39:24.838+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-03T22:20:55.980+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T22:20:55.997+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-10-01T00:00:00+00:00 [queued]>
[2024-06-03T22:20:56.003+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-10-01T00:00:00+00:00 [queued]>
[2024-06-03T22:20:56.003+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T22:20:56.012+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2021-10-01 00:00:00+00:00
[2024-06-03T22:20:56.019+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=29930) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T22:20:56.021+0000] {standard_task_runner.py:63} INFO - Started process 29932 to run task
[2024-06-03T22:20:56.021+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2021-10-01T00:00:00+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpqmp2pvkq']
[2024-06-03T22:20:56.022+0000] {standard_task_runner.py:91} INFO - Job 131: Subtask blunders_etl
[2024-06-03T22:20:56.056+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2021-10-01T00:00:00+00:00 [running]> on host f55fff24b127
[2024-06-03T22:20:56.121+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2021-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-10-01T00:00:00+00:00'
[2024-06-03T22:20:56.122+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T22:20:56.122+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T22:20:56.129+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-03T22:20:57.263+0000] {logging_mixin.py:188} INFO - No games for period 2021_10
[2024-06-03T22:20:57.263+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-03T22:20:57.264+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T22:20:57.270+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2021-10-01T00:00:00+00:00, execution_date=20211001T000000, start_date=20240603T222055, end_date=20240603T222057
[2024-06-03T22:20:57.318+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-03T22:20:57.330+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T22:20:57.332+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T19:46:45.633+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T19:46:45.648+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-10-01T00:00:00+00:00 [queued]>
[2024-06-08T19:46:45.654+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-10-01T00:00:00+00:00 [queued]>
[2024-06-08T19:46:45.655+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T19:46:45.665+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2021-10-01 00:00:00+00:00
[2024-06-08T19:46:45.672+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=30367) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T19:46:45.674+0000] {standard_task_runner.py:63} INFO - Started process 30369 to run task
[2024-06-08T19:46:45.674+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2021-10-01T00:00:00+00:00', '--job-id', '307', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpvyxtdx6p']
[2024-06-08T19:46:45.675+0000] {standard_task_runner.py:91} INFO - Job 307: Subtask blunders_etl
[2024-06-08T19:46:45.712+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2021-10-01T00:00:00+00:00 [running]> on host bf0ade909435
[2024-06-08T19:46:45.773+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2021-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-10-01T00:00:00+00:00'
[2024-06-08T19:46:45.774+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T19:46:45.775+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T19:46:45.781+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T19:46:46.748+0000] {logging_mixin.py:188} INFO - No games for period 2021_10
[2024-06-08T19:46:46.749+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T19:46:46.750+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T19:46:46.761+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2021-10-01T00:00:00+00:00, execution_date=20211001T000000, start_date=20240608T194645, end_date=20240608T194646
[2024-06-08T19:46:46.810+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T19:46:46.822+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T19:46:46.823+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-08T01:44:57.233+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T01:44:57.251+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-10-01T00:00:00+00:00 [queued]>
[2024-07-08T01:44:57.259+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-10-01T00:00:00+00:00 [queued]>
[2024-07-08T01:44:57.260+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-08T01:44:57.271+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2021-10-01 00:00:00+00:00
[2024-07-08T01:44:57.280+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2021-10-01T00:00:00+00:00', '--job-id', '689', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpz_8c4n32']
[2024-07-08T01:44:57.279+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=31218) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-08T01:44:57.281+0000] {standard_task_runner.py:91} INFO - Job 689: Subtask blunders_etl
[2024-07-08T01:44:57.282+0000] {standard_task_runner.py:63} INFO - Started process 31220 to run task
[2024-07-08T01:44:57.319+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2021-10-01T00:00:00+00:00 [running]> on host 6569f5155f0c
[2024-07-08T01:44:57.381+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2021-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-10-01T00:00:00+00:00'
[2024-07-08T01:44:57.382+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T01:44:57.383+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-07-08T01:44:57.390+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-07-08T01:44:58.406+0000] {logging_mixin.py:188} INFO - No games for period 2021_10
[2024-07-08T01:44:58.406+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-08T01:44:58.407+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T01:44:58.414+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2021-10-01T00:00:00+00:00, execution_date=20211001T000000, start_date=20240708T014457, end_date=20240708T014458
[2024-07-08T01:44:58.458+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-08T01:44:58.478+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-08T01:44:58.479+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
