[2024-06-03T17:39:14.225+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:39:14.240+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-05-01T00:00:00+00:00 [queued]>
[2024-06-03T17:39:14.247+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-05-01T00:00:00+00:00 [queued]>
[2024-06-03T17:39:14.247+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:39:14.257+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2021-05-01 00:00:00+00:00
[2024-06-03T17:39:14.262+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=209) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:39:14.263+0000] {standard_task_runner.py:63} INFO - Started process 213 to run task
[2024-06-03T17:39:14.264+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2021-05-01T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpwdw1qh92']
[2024-06-03T17:39:14.264+0000] {standard_task_runner.py:91} INFO - Job 50: Subtask blunders_etl
[2024-06-03T17:39:14.300+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2021-05-01T00:00:00+00:00 [running]> on host a5a4421409ea
[2024-06-03T17:39:14.364+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2021-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-05-01T00:00:00+00:00'
[2024-06-03T17:39:14.365+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:39:14.366+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:39:14.371+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:39:14.377+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chess_dag.py", line 23, in blunders_etl_task
    return get_monthly_blunders(execution_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/blunder_etl_code.py", line 89, in get_monthly_blunders
    connection = BaseHook.get_connection('chess_project_s3')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `chess_project_s3` isn't defined
[2024-06-03T17:39:14.384+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2021-05-01T00:00:00+00:00, execution_date=20210501T000000, start_date=20240603T173914, end_date=20240603T173914
[2024-06-03T17:39:14.392+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 50 for task blunders_etl (The conn_id `chess_project_s3` isn't defined; 213)
[2024-06-03T17:39:14.436+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-03T17:39:14.447+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:39:14.448+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-03T22:02:29.175+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T22:02:29.191+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-05-01T00:00:00+00:00 [queued]>
[2024-06-03T22:02:29.198+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-05-01T00:00:00+00:00 [queued]>
[2024-06-03T22:02:29.198+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T22:02:29.209+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2021-05-01 00:00:00+00:00
[2024-06-03T22:02:29.217+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=27846) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T22:02:29.218+0000] {standard_task_runner.py:63} INFO - Started process 27848 to run task
[2024-06-03T22:02:29.218+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2021-05-01T00:00:00+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmppv4g2_7_']
[2024-06-03T22:02:29.219+0000] {standard_task_runner.py:91} INFO - Job 121: Subtask blunders_etl
[2024-06-03T22:02:29.256+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2021-05-01T00:00:00+00:00 [running]> on host f55fff24b127
[2024-06-03T22:02:29.336+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2021-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-05-01T00:00:00+00:00'
[2024-06-03T22:02:29.337+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T22:02:29.338+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T22:02:29.345+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-03T22:17:23.507+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-03T22:17:23.507+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T22:17:23.515+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2021-05-01T00:00:00+00:00, execution_date=20210501T000000, start_date=20240603T220229, end_date=20240603T221723
[2024-06-03T22:17:23.554+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-03T22:17:23.567+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T22:17:23.569+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T19:29:20.334+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T19:29:20.348+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-05-01T00:00:00+00:00 [queued]>
[2024-06-08T19:29:20.354+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-05-01T00:00:00+00:00 [queued]>
[2024-06-08T19:29:20.354+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T19:29:20.367+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2021-05-01 00:00:00+00:00
[2024-06-08T19:29:20.374+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=28264) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T19:29:20.375+0000] {standard_task_runner.py:63} INFO - Started process 28266 to run task
[2024-06-08T19:29:20.375+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2021-05-01T00:00:00+00:00', '--job-id', '297', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpdy4haps8']
[2024-06-08T19:29:20.376+0000] {standard_task_runner.py:91} INFO - Job 297: Subtask blunders_etl
[2024-06-08T19:29:20.409+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2021-05-01T00:00:00+00:00 [running]> on host bf0ade909435
[2024-06-08T19:29:20.467+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2021-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-05-01T00:00:00+00:00'
[2024-06-08T19:29:20.469+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T19:29:20.469+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T19:29:20.475+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T19:43:23.995+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T19:43:23.996+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T19:43:24.004+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2021-05-01T00:00:00+00:00, execution_date=20210501T000000, start_date=20240608T192920, end_date=20240608T194324
[2024-06-08T19:43:24.046+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T19:43:24.058+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T19:43:24.060+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-08T01:27:19.687+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T01:27:19.701+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-05-01T00:00:00+00:00 [queued]>
[2024-07-08T01:27:19.707+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2021-05-01T00:00:00+00:00 [queued]>
[2024-07-08T01:27:19.708+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-08T01:27:19.716+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2021-05-01 00:00:00+00:00
[2024-07-08T01:27:19.723+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=29091) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-08T01:27:19.724+0000] {standard_task_runner.py:63} INFO - Started process 29093 to run task
[2024-07-08T01:27:19.724+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2021-05-01T00:00:00+00:00', '--job-id', '669', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpu9mrqm7u']
[2024-07-08T01:27:19.725+0000] {standard_task_runner.py:91} INFO - Job 669: Subtask blunders_etl
[2024-07-08T01:27:19.761+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2021-05-01T00:00:00+00:00 [running]> on host 6569f5155f0c
[2024-07-08T01:27:19.825+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2021-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-05-01T00:00:00+00:00'
[2024-07-08T01:27:19.826+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T01:27:19.827+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-07-08T01:27:19.832+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-07-08T01:41:15.798+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-08T01:41:15.799+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T01:41:15.807+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2021-05-01T00:00:00+00:00, execution_date=20210501T000000, start_date=20240708T012719, end_date=20240708T014115
[2024-07-08T01:41:15.857+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-08T01:41:15.873+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-08T01:41:15.874+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
