[2024-07-07T18:23:40.290+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T18:23:40.307+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.redshift_game_load scheduled__2020-11-01T00:00:00+00:00 [queued]>
[2024-07-07T18:23:40.314+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.redshift_game_load scheduled__2020-11-01T00:00:00+00:00 [queued]>
[2024-07-07T18:23:40.315+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-07T18:23:40.324+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): redshift_game_load> on 2020-11-01 00:00:00+00:00
[2024-07-07T18:23:40.329+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1227) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-07T18:23:40.330+0000] {standard_task_runner.py:63} INFO - Started process 1231 to run task
[2024-07-07T18:23:40.330+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'redshift_game_load', 'scheduled__2020-11-01T00:00:00+00:00', '--job-id', '434', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmpsz_w_qrr']
[2024-07-07T18:23:40.331+0000] {standard_task_runner.py:91} INFO - Job 434: Subtask redshift_game_load
[2024-07-07T18:23:40.363+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.redshift_game_load scheduled__2020-11-01T00:00:00+00:00 [running]> on host cb919e35e0e9
[2024-07-07T18:23:40.416+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='redshift_game_load' AIRFLOW_CTX_EXECUTION_DATE='2020-11-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-11-01T00:00:00+00:00'
[2024-07-07T18:23:40.417+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T18:23:40.418+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-07-07T18:23:40.424+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-07-07T18:23:41.256+0000] {base.py:84} INFO - Using connection ID 'chess_project_redshift' for task execution.
[2024-07-07T18:23:43.619+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T18:23:43.620+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chess_dag.py", line 27, in redshift_game_task
    return load_game_data(execution_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/redshift_etl_code.py", line 107, in load_game_data
    cursor.execute(drop_games_staging_query)
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/cursor.py", line 248, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/cursor.py", line 241, in execute
    self._c.execute(self, operation, args)
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/core.py", line 1987, in execute
    self.handle_messages(cursor)
  File "/home/airflow/.local/lib/python3.12/site-packages/redshift_connector/core.py", line 2194, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': 'XX000', 'M': 'could not open relation with OID 200404', 'F': '../src/pg/src/backend/access/heap/heapam.c', 'L': '636', 'R': 'local_relation_open'}
[2024-07-07T18:23:43.630+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=chess_etl, task_id=redshift_game_load, run_id=scheduled__2020-11-01T00:00:00+00:00, execution_date=20201101T000000, start_date=20240707T182340, end_date=20240707T182343
[2024-07-07T18:23:43.638+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 434 for task redshift_game_load ({'S': 'ERROR', 'C': 'XX000', 'M': 'could not open relation with OID 200404', 'F': '../src/pg/src/backend/access/heap/heapam.c', 'L': '636', 'R': 'local_relation_open'}; 1231)
[2024-07-07T18:23:43.672+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-07T18:23:43.685+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-07T18:23:43.686+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-08T00:15:35.791+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T00:15:35.805+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.redshift_game_load scheduled__2020-11-01T00:00:00+00:00 [queued]>
[2024-07-08T00:15:35.810+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.redshift_game_load scheduled__2020-11-01T00:00:00+00:00 [queued]>
[2024-07-08T00:15:35.811+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-08T00:15:35.820+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): redshift_game_load> on 2020-11-01 00:00:00+00:00
[2024-07-08T00:15:35.827+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=20499) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-08T00:15:35.829+0000] {standard_task_runner.py:63} INFO - Started process 20501 to run task
[2024-07-08T00:15:35.829+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'redshift_game_load', 'scheduled__2020-11-01T00:00:00+00:00', '--job-id', '646', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp92ll4hzw']
[2024-07-08T00:15:35.829+0000] {standard_task_runner.py:91} INFO - Job 646: Subtask redshift_game_load
[2024-07-08T00:15:35.864+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.redshift_game_load scheduled__2020-11-01T00:00:00+00:00 [running]> on host 6569f5155f0c
[2024-07-08T00:15:35.925+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='redshift_game_load' AIRFLOW_CTX_EXECUTION_DATE='2020-11-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-11-01T00:00:00+00:00'
[2024-07-08T00:15:35.926+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T00:15:35.927+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-07-08T00:15:35.933+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-07-08T00:15:36.697+0000] {base.py:84} INFO - Using connection ID 'chess_project_redshift' for task execution.
[2024-07-08T00:15:38.525+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-08T00:15:38.526+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T00:15:38.532+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=redshift_game_load, run_id=scheduled__2020-11-01T00:00:00+00:00, execution_date=20201101T000000, start_date=20240708T001535, end_date=20240708T001538
[2024-07-08T00:15:38.569+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-08T00:15:38.584+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-08T00:15:38.586+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
