[2024-06-03T17:44:34.696+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T17:44:34.714+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-03-01T00:00:00+00:00 [queued]>
[2024-06-03T17:44:34.719+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-03-01T00:00:00+00:00 [queued]>
[2024-06-03T17:44:34.720+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T17:44:34.732+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-03-01 00:00:00+00:00
[2024-06-03T17:44:34.738+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=84) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T17:44:34.739+0000] {standard_task_runner.py:63} INFO - Started process 94 to run task
[2024-06-03T17:44:34.739+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-03-01T00:00:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp2b_kzlm8']
[2024-06-03T17:44:34.740+0000] {standard_task_runner.py:91} INFO - Job 70: Subtask blunders_etl
[2024-06-03T17:44:34.781+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-03-01T00:00:00+00:00 [running]> on host f55fff24b127
[2024-06-03T17:44:34.849+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-03-01T00:00:00+00:00'
[2024-06-03T17:44:34.850+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T17:44:34.851+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-03T17:44:34.858+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-03T17:45:48.655+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-03T17:45:48.656+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T17:45:48.663+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-03-01T00:00:00+00:00, execution_date=20190301T000000, start_date=20240603T174434, end_date=20240603T174548
[2024-06-03T17:45:48.693+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-03T17:45:48.706+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T17:45:48.707+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:10:01.437+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:10:01.453+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-03-01T00:00:00+00:00 [queued]>
[2024-06-08T14:10:01.459+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-03-01T00:00:00+00:00 [queued]>
[2024-06-08T14:10:01.460+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:10:01.472+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-03-01 00:00:00+00:00
[2024-06-08T14:10:01.478+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=99) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:10:01.479+0000] {standard_task_runner.py:63} INFO - Started process 101 to run task
[2024-06-08T14:10:01.479+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-03-01T00:00:00+00:00', '--job-id', '210', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp0pys4sg2']
[2024-06-08T14:10:01.480+0000] {standard_task_runner.py:91} INFO - Job 210: Subtask blunders_etl
[2024-06-08T14:10:01.513+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-03-01T00:00:00+00:00 [running]> on host 3c9d89bfdaf1
[2024-06-08T14:10:01.578+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-03-01T00:00:00+00:00'
[2024-06-08T14:10:01.579+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:10:01.580+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:10:01.586+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:11:14.757+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:11:14.758+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chess_dag.py", line 23, in blunders_etl_task
    return get_monthly_blunders(execution_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/blunder_etl_code.py", line 109, in get_monthly_blunders
    if df_blunders['side']==0:
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 1519, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
[2024-06-08T14:11:14.769+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-03-01T00:00:00+00:00, execution_date=20190301T000000, start_date=20240608T141001, end_date=20240608T141114
[2024-06-08T14:11:14.778+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 210 for task blunders_etl (The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().; 101)
[2024-06-08T14:11:14.800+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-08T14:11:14.810+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T14:11:14.812+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-08T14:51:30.308+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T14:51:30.326+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-03-01T00:00:00+00:00 [queued]>
[2024-06-08T14:51:30.334+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chess_etl.blunders_etl scheduled__2019-03-01T00:00:00+00:00 [queued]>
[2024-06-08T14:51:30.335+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-08T14:51:30.345+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): blunders_etl> on 2019-03-01 00:00:00+00:00
[2024-06-08T14:51:30.351+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=216) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-08T14:51:30.352+0000] {standard_task_runner.py:63} INFO - Started process 220 to run task
[2024-06-08T14:51:30.352+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chess_etl', 'blunders_etl', 'scheduled__2019-03-01T00:00:00+00:00', '--job-id', '246', '--raw', '--subdir', 'DAGS_FOLDER/chess_dag.py', '--cfg-path', '/tmp/tmp_llo_e55']
[2024-06-08T14:51:30.353+0000] {standard_task_runner.py:91} INFO - Job 246: Subtask blunders_etl
[2024-06-08T14:51:30.387+0000] {task_command.py:426} INFO - Running <TaskInstance: chess_etl.blunders_etl scheduled__2019-03-01T00:00:00+00:00 [running]> on host bf0ade909435
[2024-06-08T14:51:30.453+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chess_etl' AIRFLOW_CTX_TASK_ID='blunders_etl' AIRFLOW_CTX_EXECUTION_DATE='2019-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-03-01T00:00:00+00:00'
[2024-06-08T14:51:30.455+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T14:51:30.456+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:320: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-06-08T14:51:30.462+0000] {base.py:84} INFO - Using connection ID 'chess_project_s3' for task execution.
[2024-06-08T14:52:44.765+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T14:52:44.766+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T14:52:44.772+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chess_etl, task_id=blunders_etl, run_id=scheduled__2019-03-01T00:00:00+00:00, execution_date=20190301T000000, start_date=20240608T145130, end_date=20240608T145244
[2024-06-08T14:52:44.790+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T14:52:44.801+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T14:52:44.802+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
